/** Synthetic source/control fixtures only. Never copied into archaeological datasets. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {deflateSync} from 'node:zlib';
import {build} from 'esbuild';
import {sha} from '../plate_registration/engine.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const compiled=await build({entryPoints:[path.join(repo,'src/evidence/assembly.ts')],bundle:true,write:false,format:'esm',platform:'node'});
const {buildKhafreAssembly}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
function crc(data){let c=0xffffffff;for(const b of data){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function chunk(name,data){const type=Buffer.from(name),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);type.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([type,data])),out.length-4);return out;}
export function campaignFixture(id='qa.khafre.plan'){
  const read=p=>JSON.parse(fs.readFileSync(path.join(repo,'public/model',p),'utf8'));
  const assembly=buildKhafreAssembly({parts:read('parts.json').parts,measurements:read('research/measurements.json').measurements,componentResearch:read('component_research.json'),sourceRegistry:read('evidence/source_registry.json').sources});
  const points=[[10,10],[110,20],[20,110],[105,100],[50,55],[70,85]],sectors=['NW','NE','SW','SE','CENTRE','SOUTH'];
  const header=Buffer.alloc(13);header.writeUInt32BE(128,0);header.writeUInt32BE(128,4);header[8]=8;header[9]=2;
  const raw=Buffer.alloc(128*(1+128*3),255);for(let y=0;y<128;y++){raw[y*385]=0;for(let x=0;x<128;x++)if(points.some(([px,py])=>Math.hypot(x-px,y-py)<3))raw.fill(0,y*385+1+x*3,y*385+4+x*3);}
  const png=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);
  const stream='0 0 0 rg\n'+points.map(([x,y])=>`${x-2} ${128-y-2} 4 4 re f`).join('\n')+'\nBT /F1 4 Tf 3 3 Td (SYNTHETIC SOFTWARE QA - NOT ARCHAEOLOGY) Tj ET';
  const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 128 128] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
  let document='%PDF-1.4\n% SYNTHETIC SOFTWARE QA ONLY\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(document));document+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(document);document+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;const pdf=Buffer.from(document);
  const provenance={source_id:'qa.control',locator:'Generated independent truth table; software fixture only',independent_of_fit:true};
  const sources=[{id:'qa.image',title:'SYNTHETIC point layout, NOT Giza imagery',locator:'Generated fixture page 1',underlyingSourceId:'synthetic-image',rights:{permittedUse:'Software testing only',basis:'Generated by this repository'}},{id:'qa.control',title:'SYNTHETIC independent truth table',locator:'Generated control table',underlyingSourceId:'synthetic-control',independentOfModel:true,rights:{permittedUse:'Software testing only',basis:'Generated by this repository'}}];
  const config={schema:'giza.scoped-campaign.v1',id,assemblyId:assembly.id,classification:'SYNTHETIC_SOFTWARE_QA',question:'Does the shared engine recover a declared synthetic planar similarity?',acceptanceQuestion:'All unmodified historical-plan profile gates and untouched holdouts must pass.',pageLocator:'Synthetic fixture page 1',featureIdentification:'Synthetic markers exercise coffer feature bindings; they are not surveyed endpoints.',units:'m',dimensionalScope:'PLAN_2D_ONLY',targetFrame:'frame.qa.coffer.plan.2d',primarySourceId:'qa.image',sources,thresholdProfileId:'threshold.historical_plan_similarity.v1',landmarks:points.map((_,i)=>({id:`qa.point.${i}`,sector:sectors[i],description:'Synthetic point, not archaeology',featureId:'feature.coffer.wall.west'}))};
  const input={source_sha256:sha(pdf),render_sha256:sha(png),threshold_profile_id:config.thresholdProfileId,pixel_axis:'Y_DOWN',scale_expectation:{meters_per_pixel:.02,...provenance},landmarks:points.map(([x,y],i)=>({id:`qa.point.${i}`,role:i<4?'CONTROL':'HOLDOUT',source_px:{x,y},target_m:{x:5+x*.02,y:4-y*.02},target_source:provenance,uncertainty:{status:'BOUND',value:.001}}))};
  return {config,assembly,sourcePdfBase64:pdf.toString('base64'),renderPngBase64:png.toString('base64'),controlAssets:[{sourceId:'qa.control',base64:Buffer.from(JSON.stringify(input.landmarks.map(l=>l.target_m))).toString('base64')}],visualConfirmation:true,input};
}
