import {test,expect} from '@playwright/test';
test('overview layer requests render underground, respect authority and filter inspection',async({page})=>{
  await page.goto('/?layerDiagnostics=1');
  const canvas=page.locator('canvas').first();await expect(canvas).toBeVisible();
  const ids=async()=>JSON.parse(await canvas.getAttribute('data-layer-diagnostics')??'{"ids":[]}').ids as string[];
  const underground=async()=>(await ids()).filter(id=>id.startsWith('part.shaft.')).length;
  await expect(page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true})).not.toBeChecked();await expect.poll(underground).toBe(0);
  await page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true}).check();await expect.poll(underground).toBe(8);
  await page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true}).uncheck();await expect.poll(underground).toBe(0);
  await page.getByRole('button',{name:'Underground',exact:true}).click();await expect.poll(underground).toBe(8);
  await page.getByRole('button',{name:'Inspect / layers',exact:true}).hover();await page.getByText('Reality layers',{exact:true}).click();await page.getByRole('checkbox',{name:'HYPOTHESIS',exact:true}).uncheck();await expect.poll(underground).toBe(0);
  await expect(page.getByText(/Subterranean layer is enabled but hidden/)).toBeVisible();await page.getByRole('button',{name:'Show hypothetical underground'}).click();await expect.poll(underground).toBe(8);
  await page.getByRole('checkbox',{name:'Exterior (Current)',exact:true}).uncheck();await expect.poll(async()=>(await ids()).includes('part.pyramid.khafre')).toBe(false);await expect.poll(async()=>JSON.parse((await canvas.getAttribute('data-layer-diagnostics'))!).instanced).toBe(0);
  await page.getByRole('checkbox',{name:'Internal Architecture',exact:true}).uncheck();await page.getByRole('button',{name:'Inspect / layers',exact:true}).hover();await page.getByRole('button',{name:'Remove shell / inspect inside'}).click();await expect.poll(async()=>(await ids()).length).toBe(0);
  await page.getByRole('checkbox',{name:'Internal Architecture',exact:true}).check();await expect.poll(async()=>(await ids()).some(id=>id.startsWith('part.burial.'))).toBe(true);await expect.poll(underground).toBe(0);
  await page.getByRole('button',{name:'Inspect / layers',exact:true}).hover();await page.getByRole('button',{name:'Restore shell',exact:true}).click();await page.getByRole('checkbox',{name:'Surrounding Terrain',exact:true}).uncheck();await expect.poll(async()=>(await ids()).includes('part.plateau.reference')).toBe(false);
  await page.getByRole('checkbox',{name:'Casing Stones',exact:true}).uncheck();await expect.poll(async()=>(await ids()).includes('part.casing.granite.lower')).toBe(false);
});
test('overview overlays and detail controls match their scope',async({page})=>{
  await page.goto('/?layerDiagnostics=1');
  await page.getByRole('button',{name:'Full Pyramid',exact:true}).click();
  await page.getByRole('checkbox',{name:'Show Dimensions',exact:true}).check();
  await page.getByRole('button',{name:'Inspect / layers',exact:true}).hover();
  await expect(page.getByText('Selected preview dimensions',{exact:true})).toBeVisible();
  await page.getByRole('checkbox',{name:'Measurement Overlays',exact:true}).uncheck();
  await expect(page.getByText('Selected preview dimensions',{exact:true})).toHaveCount(0);
  await page.getByRole('checkbox',{name:'Measurement Overlays',exact:true}).check();
  await page.getByRole('button',{name:'Inspect / layers',exact:true}).hover();
  await expect(page.getByText('Selected preview dimensions',{exact:true})).toBeVisible();
  await page.getByRole('checkbox',{name:'Reference Photos',exact:true}).uncheck();
  await expect(page.locator('.thumb img')).toHaveCount(0);
  await page.getByRole('checkbox',{name:'Reference Photos',exact:true}).check();
  await expect.poll(()=>page.locator('.thumb img').count()).toBeGreaterThan(0);
  await page.getByRole('button',{name:'Upper Passage',exact:true}).click();
  await expect(page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Return to model layers',exact:true}).click();
  await expect(page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true})).toBeEnabled();
  await page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true}).focus();
  await page.keyboard.press('Space');
  await expect(page.getByRole('checkbox',{name:'Subterranean (Unverified)',exact:true})).toBeChecked();
});
