import fs from 'node:fs';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const manifest=read('public/model/simlab/simlab_manifest.json');
const result=read('public/model/simlab/results/acoustic.known-interiors-screening.json');
const bench=read('public/model/simlab/benchmarks/acoustic_benchmark.json');
const parts=read('public/model/parts.json').parts;
const index=read('public/model/simlab/run_index.json');
const errors=[];
if(manifest.version!=='0.9.3') errors.push('SIMLAB/ECHO manifest version mismatch');
if(!manifest.active_solvers.includes('solver.acoustic')) errors.push('acoustic solver not active');
if(!bench.pass) errors.push('acoustic analytical benchmark failed');
if(result.provenance_class!=='SIMULATED') errors.push('acoustic result must be SIMULATED');
if(result.truth_status!=='CONDITIONAL_DERIVED_GEOMETRY') errors.push('acoustic known-interior truth guard changed');
if(!result.geometry_hash||!result.input_hash) errors.push('acoustic hashes missing');
if(!result.controls?.primary_null) errors.push('acoustic primary null missing');
if(result.selected_visualization?.points?.length<100) errors.push('3-D acoustic pressure field missing');
if(result.components?.length<10) errors.push('acoustic component network unexpectedly small');
if(result.coincidence_screen?.independent_null?.n!==200) errors.push('independent perturbation control count changed');
if(result.coincidence_screen?.constraint_preserving_null?.n!==200) errors.push('constraint-preserving control count changed');
if(result.human_summary?.design_claim_status!=='NOT_ESTABLISHED') errors.push('design claim improperly promoted');
const unverified=new Set(parts.filter(p=>p.provenance?.class==='UNVERIFIED').map(p=>p.id));
for(const c of result.components) if(unverified.has(c.part_id)) errors.push(`known-interior acoustic run includes UNVERIFIED part ${c.part_id}`);
if(parts.filter(p=>p.provenance?.class==='UNVERIFIED').length!==31) errors.push('deep-claim provenance count changed');
if(!index.runs.some(r=>r.experiment_id==='acoustic.known-interiors-screening')) errors.push('run index missing ECHO result');
console.log('GIZA // ECHO validation');
console.log(`components=${result.components.length} pressurePoints=${result.selected_visualization.points.length}`);
console.log(`burialFundamental=${result.human_summary.burial_fundamental_hz.toFixed(3)} Hz lower=${result.human_summary.lower_fundamental_hz.toFixed(3)} Hz`);
console.log(`clusters=${result.coincidence_screen.actual_cluster_count} independentNullMean=${result.coincidence_screen.independent_null.mean.toFixed(3)} constrainedNullMean=${result.coincidence_screen.constraint_preserving_null.mean.toFixed(3)}`);
console.log(`benchmark=${bench.pass?'PASS':'FAIL'} designClaim=${result.human_summary.design_claim_status}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log('PASS');
