import fs from 'node:fs';import crypto from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const errors=[];const need=(ok,msg)=>{if(!ok)errors.push(msg)};const V='0.10.7';
const manifest=read('public/model/maps/manifest.json');const sourceIds=new Set(read('public/model/evidence/source_registry.json').sources.map(s=>s.id));const synthesisIds=new Set(read('public/model/intent/synthesis.json').results.map(x=>x.hypothesis_id));const canonicalSurvey=read('public/model/control_net/survey_points.json').points;const actionGraph=read('public/model/action_graph/graph.json');const roomGraph=read('public/model/room_graph/graph.json');const visibility=read('public/model/visibility_lab/route_metrics.json');const readiness=read('public/model/metric_view_lab/metric_readiness.json');
const files={plateau:read('public/model/maps/layers/plateau_master.json'),ritual:read('public/model/maps/layers/ritual_route.json'),action:read('public/model/maps/layers/action_graph.json'),rooms:read('public/model/maps/layers/room_graph.json'),visibility:read('public/model/maps/layers/visibility_lab.json'),metric:read('public/model/maps/layers/metric_readiness.json'),survey:read('public/model/maps/layers/survey_control.json'),geology:read('public/model/maps/layers/geology_quarry.json'),history:read('public/model/maps/layers/historical_sources.json'),intent:read('public/model/maps/layers/intent_map.json'),photos:read('public/model/maps/layers/photo_coverage.json')};
need(manifest.version===V,'map manifest version drift');need(manifest.maps.length===11,`expected 11 maps, got ${manifest.maps.length}`);for(const m of manifest.maps){need(files[m.id],`manifest map missing data: ${m.id}`);need(!['FULL','GEOMETRY_WRITE'].includes(m.geometry_authority),`map ${m.id} geometry authority illegal`)}
const referenced=new Set(manifest.source_ids);for(const d of Object.values(files))for(const id of d.source_ids??[])referenced.add(id);for(const id of referenced)need(sourceIds.has(id),`map source missing ${id}`);
for(const id of ['plateau','ritual','action','rooms','visibility','metric'])need(files[id].metric===false,`${id} must remain nonmetric`);need(files.survey.metric===true,'survey must remain metric in native frame');need(files.rooms.spaces.length===roomGraph.spaces.length,'room map space drift');need(files.rooms.thresholds.length===roomGraph.thresholds.length,'room map threshold drift');need(files.visibility.spaces.length===roomGraph.spaces.length,'visibility map space drift');need(visibility.spaces.length===roomGraph.spaces.length,'visibility lab room coverage drift');need(files.action.nodes.length===actionGraph.nodes.length,'action map node drift');need(files.metric.targets.length===readiness.states.length,'metric readiness target drift');need(files.metric.metric_ray_count===0&&files.metric.registered_plan_count===0,'metric map may not claim unregistered geometry');
need(files.survey.translation_to_khafre_local==='UNRESOLVED','survey translation must remain unresolved');need(files.survey.vertical_status==='UNRESOLVED','survey vertical tie must remain unresolved');for(const p of files.survey.points){const c=canonicalSurvey.find(x=>x.id===p.id);need(Boolean(c),`survey point absent ${p.id}`);if(c){need(Math.abs(c.easting_m-p.e)<1e-9,`easting drift ${p.id}`);need(Math.abs(c.northing_m-p.n)<1e-9,`northing drift ${p.id}`)}}
for(const id of files.intent.hypothesis_ids)need(synthesisIds.has(id),`intent map hypothesis missing ${id}`);
const spatial=fs.readFileSync('src/workstation/SpatialViewport.tsx','utf8'),atlas=fs.readFileSync('src/maps/MapAtlasPanel.tsx','utf8'),left=fs.readFileSync('src/workstation/LeftRail.tsx','utf8'),app=fs.readFileSync('src/App.tsx','utf8'),css=fs.readFileSync('src/styles.css','utf8');need(spatial.includes('MAP ATLAS'),'viewport switch missing');need(atlas.includes('mapAtlasScroller'),'scroll atlas missing');need(atlas.includes('RoomGraphMap'),'room graph UI missing');need(atlas.includes('VisibilityLabMap'),'visibility lab UI missing');need(atlas.includes('MetricReadinessMap'),'metric readiness UI missing');need(left.includes("onOpenAtlas('rooms')"),'left rail room map link missing');need(app.includes("key === 'm'"),'M map toggle missing');need(css.includes('.roomGraphSvg'),'room graph CSS missing');need(css.includes('.visibilityLabSvg'),'visibility lab CSS missing');need(css.includes('.metricReadinessSvg'),'metric readiness CSS missing');need(css.includes('.edgeWorkspace{grid-template-columns:252px minmax(0,1fr) 410px'),'locked shell grid missing');
if(errors.length){console.error('GIZA v0.10.7 FIRST-PLATE REGISTRATION + HOLDOUT GATE map validation FAILED');errors.forEach(e=>console.error('- '+e));process.exit(1)}const digest=crypto.createHash('sha256').update(fs.readFileSync('public/model/maps/manifest.json')).digest('hex').slice(0,12);console.log(`GIZA v0.10.7 map validation maps=11 room_spaces=${files.rooms.spaces.length} visibility_spaces=${files.visibility.spaces.length} metric_targets=${files.metric.targets.length} survey_points=${files.survey.points.length} manifest=${digest}`);console.log('registered_plans=0 metric_visibility_rays=0 geometry_write=NONE shell=LOCKED scroll_atlas=READY');console.log('PASS');
