import fs from 'node:fs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const write=(p,v)=>{fs.mkdirSync(p.split('/').slice(0,-1).join('/'),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')};
const V='0.10.7';
const room=read('public/model/room_graph/graph.json');const statesDoc=read('public/model/visibility_lab/states.json');const obs=new Map(read('public/model/observatory/observations.json').observations.map(o=>[o.id,o]));
const spaces=room.spaces;const ids=new Set(spaces.map(s=>s.id));
for(const st of statesDoc.states){if(!ids.has(st.space_id))throw new Error(`visibility state unknown space ${st.space_id}`);for(const id of st.basis??[])if(!obs.has(id))throw new Error(`${st.space_id}: missing basis ${id}`)}
const stateMap=new Map(statesDoc.states.map(s=>[s.space_id,s]));
// directed graph + synthetic exterior links for pyramid entries not represented by room thresholds
const edges=[];for(const t of room.thresholds){edges.push({from:t.from,to:t.to,id:t.id,kind:t.kind,status:t.status})}
for(const id of ['room.py.upper_entry','room.py.lower_entry'])edges.push({from:'EXTERIOR',to:id,id:`synthetic.${id}.exterior`,kind:'MONUMENT_ENTRANCE_CONTEXT',status:'TOPOLOGY_SEED_ONLY'});
const adj=new Map();const und=new Map();
function add(map,a,b){if(!map.has(a))map.set(a,[]);map.get(a).push(b)}
for(const e of edges){add(adj,e.from,e.to);add(und,e.from,e.to);add(und,e.to,e.from)}
// BFS depth
const depth=new Map([['EXTERIOR',0]]),q=['EXTERIOR'];while(q.length){const a=q.shift();for(const b of adj.get(a)??[]){if(!depth.has(b)){depth.set(b,depth.get(a)+1);q.push(b)}}}
// indegree/outdegree
const indeg=new Map(),outdeg=new Map();for(const e of edges){outdeg.set(e.from,(outdeg.get(e.from)||0)+1);indeg.set(e.to,(indeg.get(e.to)||0)+1)}
// articulation points by brute force over undirected graph; count reachable among room nodes from first remaining node.
function componentsWithout(skip){const nodes=[...ids].filter(x=>x!==skip);if(!nodes.length)return 0;const seen=new Set();let c=0;for(const start of nodes){if(seen.has(start))continue;c++;const qq=[start];seen.add(start);while(qq.length){const a=qq.shift();for(const b of und.get(a)??[]){if(b==='EXTERIOR'||b===skip||!ids.has(b)||seen.has(b))continue;seen.add(b);qq.push(b)}}}return c}
const baseComp=componentsWithout(null);const articulation=[];for(const id of ids){if(componentsWithout(id)>baseComp)articulation.push(id)}
const spaceMetrics=spaces.map(s=>{const st=stateMap.get(s.id);return {space_id:s.id,label:s.label,complex:s.complex,topological_depth:depth.get(s.id)??null,in_degree:indeg.get(s.id)||0,out_degree:outdeg.get(s.id)||0,is_branch:(outdeg.get(s.id)||0)>1,is_merge:(indeg.get(s.id)||0)>1,is_articulation:articulation.includes(s.id),visibility_state:st?.state??s.visibility??'UNCLASSIFIED',environment:st?.environment??'UNCLASSIFIED',certainty:st?.certainty??'UNCLASSIFIED',basis:st?.basis??s.evidence??[],geometry_write_authority:'NONE'};});
// transition contrast categories
const rank={EXTERIOR:0,THRESHOLD:1,INTERIOR:2,PILLARED_INTERIOR:3,ENCLOSED_ROUTE:4,BRANCH_THRESHOLD:2,INTERIOR_HALL:3,'COURT / SKY_STATE_NOT_METRICALLY_MODELED':2,CIRCULATION:2,INNER_ROOMS:4,COURT_THRESHOLD:1,INTERIOR_PASSAGE:4,CLOSURE:5,CHAMBER:5,BURIAL_CHAMBER:6};
const transitions=[];for(const e of edges){if(e.from==='EXTERIOR'&&!ids.has(e.to))continue;const a=e.from==='EXTERIOR'?{environment:'EXTERIOR',state:'EXTERIOR'}:stateMap.get(e.from);const b=stateMap.get(e.to);if(!b)continue;const contrast=Math.abs((rank[b.environment]??2)-(rank[a?.environment??'EXTERIOR']??0));transitions.push({threshold_id:e.id,from:e.from,to:e.to,from_environment:a?.environment??'EXTERIOR',to_environment:b.environment,contrast_index:contrast,contrast_class:contrast>=3?'HIGH':contrast===2?'MODERATE':'LOW',status:e.status,guard:'Contrast index is a topology/display heuristic, not a physiological, ritual, or emotional measure.'})}
const route={schema_version:'1.0.0',version:V,space_count:spaceMetrics.length,articulation_count:articulation.length,branch_count:spaceMetrics.filter(x=>x.is_branch).length,merge_count:spaceMetrics.filter(x=>x.is_merge).length,max_topological_depth:Math.max(...spaceMetrics.map(x=>x.topological_depth??0)),spaces:spaceMetrics,articulation_points:articulation,guard:'Depth, branch, merge and articulation values are graph-topology metrics. Visibility states are qualitative until metric plan registration.'};
const trans={schema_version:'1.0.0',version:V,transition_count:transitions.length,high_contrast_count:transitions.filter(x=>x.contrast_class==='HIGH').length,transitions};
const map={id:'visibility',version:V,title:'Visibility / Access Lab',coordinate_mode:'SCHEMATIC_TOPOLOGY_PREMETRIC_VISIBILITY',metric:false,guard:'This view shows topological depth, access chokepoints and qualitative visibility/environment states. It does not compute metric sightlines, illumination, field of view, or ancient experience.',source_ids:[...new Set(spaceMetrics.flatMap(s=>s.basis.map(id=>obs.get(id)?.source_id)).filter(Boolean))],spaces:spaces.map(s=>{const m=spaceMetrics.find(x=>x.space_id===s.id);return {id:s.id,label:s.label,complex:s.complex,x:s.x,y:s.y,kind:s.kind,topological_depth:m.topological_depth,is_branch:m.is_branch,is_merge:m.is_merge,is_articulation:m.is_articulation,visibility_state:m.visibility_state,environment:m.environment,certainty:m.certainty};}),thresholds:room.thresholds,transitions,layers:['rooms','visibility','sources','uncertainty']};
const manifest={schema_version:'1.0.0',version:V,codename:'VISIBILITY LAB',purpose:'Pre-metric access/visibility analysis over the source-addressed ROOM GRAPH. Quantifies topological depth, branch/merge structure, chokepoints and environmental-state transitions while refusing metric line-of-sight claims.',counts:{spaces:spaceMetrics.length,transitions:transitions.length,articulation_points:articulation.length,branches:spaceMetrics.filter(x=>x.is_branch).length,merges:spaceMetrics.filter(x=>x.is_merge).length,qualitative_states:statesDoc.states.length},truth_rules:['schematic coordinates cannot produce metric rays','visibility state is qualitative until wall polygons/heights are registered','topological chokepoint is not ritual restriction','contrast index is not psychological intensity','visibility lab cannot write geometry or historical intent'],generated_at:new Date().toISOString()};
write('public/model/visibility_lab/route_metrics.json',route);write('public/model/visibility_lab/transition_analysis.json',trans);write('public/model/visibility_lab/manifest.json',manifest);write('public/model/maps/layers/visibility_lab.json',map);
console.log(`VISIBILITY LAB spaces=${spaceMetrics.length} transitions=${transitions.length} articulation=${articulation.length} maxDepth=${route.max_topological_depth}`);
