export const INSCRIPTION = {
  id:'sphinx.dream-stela',title:'Dream Stela · Thutmose IV',
  context:'The inscribed stela between the Sphinx’s forepaws. These images document the inscription, not the age or internal geometry of the Sphinx.',
  limitation:'Weathering, lighting, historical copying and photographic resolution affect readings. No automatic translation or recovered missing text is claimed.',
};
export const INSCRIPTION_IMAGES = [
  {id:'dream-detail',title:'Dream Stela · carved detail',kind:'Detail photograph',
    image:'/epigraphy/dream-stela-detail.jpg',width:3264,height:2448,
    original:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Gizeh-Stele_du_reve.jpg',
    source:'https://commons.wikimedia.org/wiki/File:Gizeh-Stele_du_reve.jpg',
    author:'Kurohito',date:'2008-04',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',
    note:'Unaltered oblique detail photograph. Perspective and weathering limit sign readings; this is not an orthophoto or a complete line transcription.'},
  {id:'dream-photo',title:'Dream Stela · photograph',kind:'Photograph',
    image:'/epigraphy/dream-stela.jpg',width:1200,height:1600,
    original:'https://upload.wikimedia.org/wikipedia/commons/2/21/Dream-stela.jpg',
    source:'https://commons.wikimedia.org/wiki/File:Dream-stela.jpg',
    author:'HoremWeb',date:'2006-11-06',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',
    note:'Unaltered source photograph. Contrast and grayscale are temporary display adjustments; they do not recover lost marks.'},
  {id:'dream-lepsius',title:'Dream Stela · Lepsius facsimile',kind:'Historical facsimile',
    image:'/epigraphy/dream-stela-lepsius.jpg',width:1268,height:1707,
    original:'https://upload.wikimedia.org/wikipedia/commons/c/cf/Giseh_Traumstele_%28Lepsius%29_01.jpg',
    source:'https://commons.wikimedia.org/wiki/File:Giseh_Traumstele_(Lepsius)_01.jpg',
    author:'Carl Richard Lepsius',date:'1849',license:'Public domain',licenseUrl:'https://creativecommons.org/publicdomain/mark/1.0/',
    note:'Denkmaeler aus Aegypten und Aethiopien, Band V, Neues Reich, plate 69. A historical interpretation—not an independent photograph or ground truth.'},
  {id:'dream-context-wheeler',title:'Sphinx and Dream Stela · placement context',kind:'Context photograph',
    image:'/epigraphy/dream-stela-context-wheeler.jpg',width:2112,height:2816,
    original:'https://upload.wikimedia.org/wikipedia/commons/d/d9/Great_Sphinx_with_Stelae.jpg',
    source:'https://commons.wikimedia.org/wiki/File:Great_Sphinx_with_Stelae.jpg',
    author:'Chanel Wheeler',date:'2009-03-03',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',
    note:'Unaltered context photograph. Locates the stela between the forepaws; not a metric registration or a close-up for resolving damaged signs.'},
  {id:'dream-reproduction-detail',title:'Dream Stela · museum reproduction detail',kind:'REPRODUCTION photograph',
    image:'/epigraphy/dream-stela-reproduction-detail.png',width:2048,height:1536,
    original:'https://upload.wikimedia.org/wikipedia/commons/b/b5/ReproductionOfDreamSteleOfThutmoseIV-CloseUp_RosicrucianEgyptianMuseum.png',
    source:'https://commons.wikimedia.org/wiki/File:ReproductionOfDreamSteleOfThutmoseIV-CloseUp_RosicrucianEgyptianMuseum.png',
    author:'Captmondo',date:'2007-02-07',license:'CC BY-SA 2.5',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.5/',
    note:'Unaltered photograph of a modern museum reproduction, RC 1834, Rosicrucian Egyptian Museum. Useful for comparing the offering scene and signs; NOT direct evidence of surviving marks, ancient color or missing text on the original.'},
] as const;
export const EPIGRAPHY_REFERENCES = [
  {title:'NYPL · 5,072 × 6,299 historical stela plate (alternate scan, not independent evidence)',url:'https://digitalcollections.nypl.org/items/510d47d9-5951-a3d9-e040-e00a18064a99'},
  {title:'Harvard Museum · Dream Stela cast and interpretation (not the original stone)',url:'https://hmane.harvard.edu/dream-stela'},
  {title:'TLA · scholarly text corpus & dictionary',url:'https://thesaurus-linguae-aegyptiae.de/search?lang=en'},
  {title:'Unicode 17 · sign character identities (not translations)',url:'https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt'},
  {title:'Digital Rosetta Stone · text / image alignment research',url:'https://www.digital-rosetta-stone.org/'},
];
