import {useRef,useState,type PointerEvent} from 'react';
import type {INSCRIPTION_IMAGES} from './catalog';
import {updateReading,type Point,type Region} from './model';
type Source=typeof INSCRIPTION_IMAGES[number];
const path=(points:Point[])=>points.map((p,i)=>`${i?'L':'M'}${p[0]*1000},${p[1]*1000}`).join(' ');
const palette=[['Red ochre','#a33c26'],['Yellow ochre','#c39a3b'],['Blue hypothesis','#3277a8'],['Carbon dark','#292722']] as const;
export function RestorationStudio({source,selected,onChange,onCreate,onDetail}:{source:Source;selected?:Region;onChange:(r:Region)=>void;onCreate:()=>void;onDetail:()=>void}){
  const [view,setView]=useState<'SKETCH'|'AI'>('SKETCH'),[color,setColor]=useState('#a33c26'),[width,setWidth]=useState(.008),[opacity,setOpacity]=useState(.65),[paint,setPaint]=useState(false),[draft,setDraft]=useState<Point[]>([]),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false);
  const stroke=useRef<Point[]>([]),pointer=useRef<number|null>(null);
  const [zoom,setZoom]=useState(100);
  const prediction=selected?.restoration;
  const edit=(patch:Partial<NonNullable<typeof prediction>>)=>{if(selected&&prediction)onChange(updateReading(selected,{restoration:{...prediction,...patch,status:'PREDICTION',pigmentEvidence:'NOT_ESTABLISHED'}}));};
  const point=(e:PointerEvent<SVGSVGElement>):Point=>{const b=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))];};
  const clear=()=>{pointer.current=null;stroke.current=[];setDraft([]);};
  const finish=(e:PointerEvent<SVGSVGElement>)=>{if(pointer.current!==e.pointerId)return;const points=[...stroke.current,point(e)].slice(0,1000);if(prediction&&prediction.strokes.length<100)edit({strokes:[...prediction.strokes,{points,color,width}]});clear();};
  return <section className="epiRestoration" aria-label="Restoration hypotheses">
    <header><small>VISUAL PREDICTIONS / NEVER SOURCE EVIDENCE</small><h2>Imagine the color. Keep the uncertainty.</h2><p>Original pixels stay untouched. Color choices and missing-mark interpretations are proposals, not recovered archaeology.</p></header>
    <div className="epiSourceTools"><button aria-pressed={view==='SKETCH'} onClick={()=>{setView('SKETCH');setPaint(false);}}>My color hypothesis</button><button aria-pressed={view==='AI'} disabled={source.id!=='dream-detail'} onClick={()=>{setView('AI');setPaint(false);}}>AI color concept · unvalidated</button>{source.id!=='dream-detail'&&<button onClick={onDetail}>Open detail photo for AI comparison</button>}</div>
    <div className="epiSourceTools"><label>Compare zoom <input aria-label="Restoration comparison zoom" type="range" min="100" max="300" step="25" value={zoom} onChange={e=>setZoom(+e.target.value)}/>{zoom}%</label>{view==='SKETCH'&&selected&&<button disabled={!loaded||failed||prediction!.strokes.length>=100} aria-pressed={paint} onClick={()=>setPaint(v=>!v)}>{paint?'Drawing enabled':'Enable brush'}</button>}<small>Scroll each image to inspect. Visual comparison is not registration.</small></div>
    <div className="epiCompare">
      <figure><figcaption>ORIGINAL {source.kind.toUpperCase()} · UNALTERED</figcaption><div className="epiComparisonFrame"><div style={{width:`${zoom}%`}}><img src={source.image} alt={`Unaltered ${source.title}`} onError={()=>setFailed(true)}/></div></div></figure>
      <figure className="epiPredicted"><figcaption>PREDICTION · {view==='AI'?'AI-GENERATED CONCEPT':'OPERATOR COLOR SKETCH'} · NOT VERIFIED</figcaption>{view==='AI'?<><div className="epiComparisonFrame"><div style={{width:`${zoom}%`}}><img src="/epigraphy/dream-stela-color-hypothesis-v1.png" alt="AI-generated hypothetical coloring of the Dream Stela; not archaeological evidence" onError={()=>setFailed(true)}/></div></div><p>Pre-generated example, not live AI. It may alter contours or marks. Do not read generated signs as text or use this image for measurement.</p></>:<div className="epiComparisonFrame"><div className="epiPaintPlane" style={{width:`${zoom}%`}}><img src={source.image} alt="Photograph beneath a separate predictive color layer" draggable={false} onLoad={()=>setLoaded(true)} onError={()=>setFailed(true)}/><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Predictive color sketch surface" style={{touchAction:paint?'none':'auto',cursor:paint?'crosshair':'default'}} onPointerDown={e=>{if(!paint||!selected||!loaded||failed||e.button!==0||prediction!.strokes.length>=100)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointer.current=e.pointerId;stroke.current=[point(e)];setDraft(stroke.current);}} onPointerMove={e=>{if(pointer.current!==e.pointerId)return;stroke.current=[...stroke.current.slice(0,998),point(e)];setDraft(stroke.current);}} onPointerUp={finish} onPointerCancel={clear}>
        <g opacity={opacity}>{prediction?.strokes.map((s,i)=><path key={i} d={path(s.points)} fill="none" stroke={s.color} strokeWidth={s.width*1000} strokeLinecap="round" strokeLinejoin="round"/>)}{draft.length>1&&<path d={path(draft)} fill="none" stroke={color} strokeWidth={width*1000} strokeLinecap="round"/>}</g>
      </svg><span className="epiPredictionWatermark">PREDICTED COLOR · NOT EVIDENCE</span></div></div>}</figure>
    </div>
    {failed&&<p role="alert">An image failed to load. Use the credited original source link below; no reconstruction is substituted for it.</p>}
    {view==='SKETCH'&&<div className="epiPaintControls">{!selected?<><p>Create or select a reading zone to save your color hypothesis with that image. It starts blank.</p><button onClick={onCreate}>Create hypothesis workspace</button></>:<><p>Saved with: <b>{selected.label}</b> · {prediction!.strokes.length}/100 strokes. Normalized coordinates refer to the whole source image; the zone is the notebook grouping, not a calibrated surface.</p><div className="epiSourceTools"><button disabled={!loaded||failed||prediction!.strokes.length>=100} aria-pressed={paint} onClick={()=>setPaint(v=>!v)}>{paint?'Stop painting':'Paint predicted color'}</button><button disabled={!prediction!.strokes.length} onClick={()=>edit({strokes:prediction!.strokes.slice(0,-1)})}>Undo color stroke</button>{palette.map(([name,hex])=><button key={hex} aria-label={name} aria-pressed={color===hex} onClick={()=>setColor(hex)}><i style={{background:hex}}/>{name}</button>)}</div><label>Brush width <input aria-label="Prediction brush width" type="range" min=".002" max=".04" step=".002" value={width} onChange={e=>setWidth(+e.target.value)}/></label><label>Layer opacity <input aria-label="Prediction layer opacity" type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(+e.target.value)}/>{Math.round(opacity*100)}%</label><label>Why this reconstruction?<textarea maxLength={4000} value={prediction!.rationale} onChange={e=>edit({rationale:e.target.value})} placeholder="Describe visual clues, comparisons and sources. A plausible color is not proof of pigment."/></label><label>Alternatives / what remains unknown<textarea maxLength={4000} value={prediction!.alternatives} onChange={e=>edit({alternatives:e.target.value})}/></label></>}</div>}
    <footer><p><b>Pigment evidence for this reconstruction: NOT ESTABLISHED.</b> No numerical confidence is invented. Notebook export includes sketches and rationale; translation review never upgrades these predictions to evidence.</p><p>Source: {source.author} · {source.date} · <a href={source.licenseUrl} target="_blank" rel="noreferrer">{source.license}</a> · <a href={source.source} target="_blank" rel="noreferrer">Original record ↗</a>. Predicted adaptations retain applicable source-license terms.</p>{view==='AI'&&<p><a href="/epigraphy/RECONSTRUCTION-RECEIPT.md" target="_blank" rel="noreferrer">AI prompt, source identity, rights and limitations ↗</a></p>}</footer>
  </section>;
}
