import {verifyFrozenExperiment,hashObject,VERSION} from './engine.mjs';
import fs from 'node:fs';
import crypto from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const errors=[]; const need=(x,m)=>{if(!x)errors.push(m)}; const V='0.10.11';
const w=read('public/model/plate_registration/remote_plate_witness.json'),d=read('public/model/plate_registration/dimension_graph.json'),q=read('public/model/plate_registration/registration_readiness.json'),m=read('public/model/plate_registration/manifest.json'),t=read('public/model/plate_registration/preregistered_thresholds.json'),f=read('public/model/plate_registration/frames.json'),c=read('public/model/plate_registration/first_plate_campaign.json'),x=read('public/model/plate_registration/cross_source_holdout.json'),b=read('public/model/plate_registration/benchmark_result.json'),s=read('public/model/source_byte_registration/candidates.json'),fp=read('public/model/plate_registration/remote_file_fingerprint.json'),lp=read('public/model/plate_registration/landmark_protocol.json'),h=read('public/model/plate_registration/custody_handoff.json');
// Product version is validated by CONTINUITY; unchanged evidence artifacts retain their own version.
for(const z of [w,d,q,m,t,f,c,x,b,fp,lp,h]) need(typeof z.version==='string','artifact version missing');
need(m.counts.actual_registered_plans===0,'canonical registered plan count must remain zero until manual promotion'); need(m.counts.actual_metric_rays===0,'canonical archaeological metric rays must remain zero');
need(t.profiles.every(p=>p.outlier_policy==='NO_AUTOMATIC_OUTLIER_REMOVAL'),'outlier policy drift'); need(t.profiles.every(p=>String(p.holdout_policy).toLowerCase().includes('excluded from fit')),'holdout exclusion rule missing'); need(f.frames.some(q=>q.id==='PLATE_LOCAL_METERS'&&q.global_translation==='UNRESOLVED'),'plate-local frame separation missing');
need(w.pdf_page_1_indexed===305&&w.printed_scale==='1:200','Plate VI remote locator/scale drift'); need(w.raw_byte_verified===false&&w.pixel_coordinate_authority==='NONE','remote witness must have zero pixel authority'); need(fp.provider_displayed.page_count===315&&fp.cryptographic_authority==='NONE','remote fingerprint drift or illegal crypto authority');
need(lp.landmarks.length>=10,'landmark protocol unexpectedly small'); need(lp.landmarks.every(z=>z.source_px===null&&z.target_m===null&&z.frozen===false),'template landmarks must remain coordinate-free'); need(lp.coordinate_authority==='NONE_UNTIL_LOCAL_CHECKSUM_BOUND_RENDER','landmark template authority drift');
need(d.fact_count===d.facts.length&&d.fact_count>=20,'dimension graph unexpectedly small'); need(d.authority['2d_wall_polygons']==='NONE'&&d.authority.visibility_rays==='NONE','dimension graph illegally promoted geometry'); need(x.state==='WAITING_FOR_INDEPENDENT_REGISTRATIONS','cross-source holdout state drift'); need(b.passed===true&&b.authority_effect===false,'synthetic benchmark must pass with zero authority');
const petrie=s.candidates.find(z=>z.id==='bytes.petrie1883.public_domain_pdf');
if(!petrie?.raw_byte_verified){need(c.controls.length===0&&c.holdouts.length===0,'controls/holdouts cannot exist before raw bytes'); need(!fs.existsSync('public/model/plate_registration/first_plate_result.json'),'fit result cannot exist before raw bytes'); need(h.local_custody.sha256===null,'custody hash present without raw bytes'); need(q.checks.metric_visibility_rays===false,'metric visibility cannot clear before raw bytes');}
if(c.controls.length||c.holdouts.length){try{verifyFrozenExperiment(process.cwd());}catch(e){errors.push(e.code??e.message);}need(c.freeze_state==='FROZEN_BEFORE_FIT','coordinate set exists but is not frozen'); need(h.local_custody.visual_confirmation===true,'coordinate set frozen before plate visual confirmation'); need(c.controls.length>=4&&c.holdouts.length>=2,'frozen control/holdout minimums not met'); need(c.source_sha256===petrie.sha256,'campaign source hash mismatch'); need(c.render_sha256===h.local_custody.plate_vi_render_sha256,'campaign render hash mismatch');}
if(h.local_custody.plate_vi_render_path){need(fs.existsSync(h.local_custody.plate_vi_render_path),'custody render path missing');if(fs.existsSync(h.local_custody.plate_vi_render_path)){const hash=crypto.createHash('sha256').update(fs.readFileSync(h.local_custody.plate_vi_render_path)).digest('hex');need(hash===h.local_custody.plate_vi_render_sha256,'custody render hash mismatch');}}
if(fs.existsSync('public/model/plate_registration/first_plate_result.json')){const r=read('public/model/plate_registration/first_plate_result.json'); need(r.version===VERSION,'first plate result version drift');const receipt={...r};delete receipt.result_sha256;need(hashObject(receipt)===r.result_sha256,'result receipt hash mismatch'); need(r.source_sha256===petrie.sha256,'first plate result source hash mismatch'); need(c.freeze_state==='FROZEN_BEFORE_FIT','fit result exists without frozen set'); need(r.geometry_authority===(r.passed?'PLATE_LOCAL_METRIC_CANDIDATE_REQUIRES_MANUAL_REVIEW':'NONE'),'fit authority/result mismatch');}
if(errors.length){console.error('PLATE REGISTRATION validation FAILED');errors.forEach(e=>console.error('- '+e));process.exit(1)} console.log(`PLATE REGISTRATION PASS threshold_profiles=${t.profiles.length} synthetic=PASS raw=${petrie?.raw_byte_verified?1:0} controls=${c.controls.length} holdouts=${c.holdouts.length} canonical_registered=0 metric_rays=0`);
