import fs from 'node:fs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const write=(p,v)=>{fs.mkdirSync(p.split('/').slice(0,-1).join('/'),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')}; const V='0.10.7';
const spaces=read('public/model/room_graph/spaces.json'), thresholds=read('public/model/room_graph/thresholds.json'), constraints=read('public/model/room_graph/constraints.json'), findspots=read('public/model/room_graph/findspot_links.json');
const obs=read('public/model/observatory/observations.json').observations; const obsMap=new Map(obs.map(o=>[o.id,o])); const ids=new Set(spaces.spaces.map(s=>s.id));
for(const s of spaces.spaces){for(const id of s.evidence??[]){if(!obsMap.has(id))throw new Error(`${s.id}: missing evidence ${id}`)}s.geometry_authority='NONE';}
for(const t of thresholds.thresholds){if(t.from!=='EXTERIOR'&&!ids.has(t.from))throw new Error(`${t.id}: bad from ${t.from}`);if(t.to!=='EXTERIOR'&&!ids.has(t.to))throw new Error(`${t.id}: bad to ${t.to}`);for(const id of t.evidence??[])if(!obsMap.has(id))throw new Error(`${t.id}: missing evidence ${id}`);t.geometry_authority='NONE';}
const sourceIds=[...new Set(spaces.spaces.flatMap(s=>(s.evidence??[]).map(id=>obsMap.get(id)?.source_id)).filter(Boolean))];
spaces.version=V;spaces.space_count=spaces.spaces.length;thresholds.version=V;thresholds.threshold_count=thresholds.thresholds.length;constraints.version=V;findspots.version=V;
const graph={schema_version:'1.0.0',version:V,graph_id:'giza.khafre.room_graph',coordinate_mode:'SCHEMATIC_TOPOLOGY_NOT_SURVEY',guard:'Room nodes encode source-backed or explicitly reconstructed topology. Coordinates are UI-only. The graph cannot write canonical geometry or claim recovered ritual choreography.',space_count:spaces.spaces.length,threshold_count:thresholds.thresholds.length,spaces:spaces.spaces,thresholds:thresholds.thresholds,constraints,findspot_links:findspots.links,canonical_geometry_mutation:false};
const map={id:'rooms',version:V,title:'Room / Threshold Graph',coordinate_mode:'SCHEMATIC_ROOM_TOPOLOGY_NOT_SURVEY',metric:false,guard:'Rooms and thresholds are source-addressed topology. UI coordinates are schematic. No line here is a surveyed wall, and no connection proves ritual choreography.',source_ids:sourceIds,spaces:spaces.spaces.map(s=>({id:s.id,complex:s.complex,label:s.label,kind:s.kind,x:s.x,y:s.y,status:s.status,access:s.access,visibility:s.visibility,evidence:s.evidence})),thresholds:thresholds.thresholds.map(t=>({id:t.id,from:t.from,to:t.to,kind:t.kind,status:t.status,evidence:t.evidence})),layers:['monuments','rooms','ritual','sources','uncertainty']};
const manifest=read('public/model/room_graph/manifest.json');manifest.version=V;manifest.counts={spaces:spaces.spaces.length,thresholds:thresholds.thresholds.length,complex_zones:new Set(spaces.spaces.map(s=>s.complex)).size,visibility_constraints:constraints.visibility_constraints.length,movement_constraints:constraints.movement_constraints.length,findspot_links:findspots.links.length};manifest.generated_at=new Date().toISOString();
write('public/model/room_graph/spaces.json',spaces);write('public/model/room_graph/thresholds.json',thresholds);write('public/model/room_graph/constraints.json',constraints);write('public/model/room_graph/findspot_links.json',findspots);write('public/model/room_graph/graph.json',graph);write('public/model/room_graph/manifest.json',manifest);write('public/model/maps/layers/room_graph.json',map);
console.log(`ROOM GRAPH spaces=${spaces.spaces.length} thresholds=${thresholds.thresholds.length} sources=${sourceIds.length}`);
