import fs from 'node:fs';
import crypto from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const errors=[]; const need=(x,m)=>{if(!x)errors.push(m)}; const V='0.10.11';
const m=read('public/model/source_byte_registration/manifest.json'),c=read('public/model/source_byte_registration/candidates.json'),l=read('public/model/source_byte_registration/page_locators.json'),r=read('public/model/source_byte_registration/rights_gates.json'),j=read('public/model/source_byte_registration/registration_jobs.json'),rr=read('public/model/source_byte_registration/remote_receipts.json'),a=read('public/model/source_byte_registration/acquisition_attempts.json'),h=read('public/model/plate_registration/custody_handoff.json'),sources=new Set(read('public/model/evidence/source_registry.json').sources.map(x=>x.id));
for(const d of [m,c,l,r,j,rr,a,h]) need(d.version===V,'source-byte/custody version drift');
need(c.candidates.length===4,'expected 4 source-byte candidates'); need(l.locators.length>=10,'expected >=10 source locators'); need(j.jobs.length>=6,'expected >=6 registration jobs'); need(rr.receipts.length>=4,'expected remote identity receipts'); need(a.attempts.length>=4,'expected >=4 acquisition-attempt receipts'); need(a.attempt_count===a.attempts.length,'attempt count drift');
need(rr.receipts.some(x=>x.id==='remote.petrie.petrieproject_pdf'&&x.local_byte_authority==='NONE'),'Petrie Project remote witness receipt missing');
let rawCount=0;
for(const x of c.candidates){
  need(sources.has(x.source_id),`${x.id}: unknown source ${x.source_id}`);
  if(x.raw_byte_verified){ rawCount++; need(Boolean(x.local_path)&&fs.existsSync(x.local_path),`${x.id}: raw verified without local bytes`); need(Boolean(x.sha256)&&x.sha256.length===64,`${x.id}: raw verified without sha256`); if(x.local_path&&fs.existsSync(x.local_path)){const hash=crypto.createHash('sha256').update(fs.readFileSync(x.local_path)).digest('hex'); need(hash===x.sha256,`${x.id}: sha256 mismatch`);} }
}
need(r.gates.some(x=>x.candidate_id==='bytes.hoelscher1912.heidelberg'&&x.gate==='BLOCK_IMAGE_BUNDLE'),'Hölscher image-rights gate missing'); need(r.gates.some(x=>x.candidate_id==='bytes.petrie1883.public_domain_pdf'&&x.gate==='ALLOW_LOCAL_ACQUISITION'),'Petrie acquisition gate missing');
for(const x of rr.receipts) need(x.local_byte_authority==='NONE',`${x.id}: remote receipt may not grant byte authority`);
for(const x of a.attempts){ if(x.result==='FAILED'){need(x.authority_effect==='NONE',`${x.id}: failed acquisition changed authority`); need(x.local_file_created===false,`${x.id}: failed attempt claims local file`);} if(x.result==='SUCCESS_LOCAL_IMPORT'){need(x.local_file_created===true,`${x.id}: successful local import lacks local file flag`);need(typeof x.sha256==='string'&&x.sha256.length===64,`${x.id}: successful local import lacks sha256`);} }
for(const x of l.locators) need(c.candidates.some(y=>y.id===x.candidate_id),`${x.id}: missing candidate`); for(const x of j.jobs){need(c.candidates.some(y=>y.id===x.candidate_id),`${x.id}: missing candidate`); need(l.locators.some(y=>y.id===x.locator_id),`${x.id}: missing locator`);}
const petrie=c.candidates.find(x=>x.id==='bytes.petrie1883.public_domain_pdf'); if(petrie?.raw_byte_verified){need(h.local_custody.sha256===petrie.sha256,'custody handoff/source candidate hash mismatch');need(h.local_custody.path===petrie.local_path,'custody handoff/source candidate path mismatch');} else {need(h.local_custody.sha256===null,'custody claims hash without raw Petrie bytes');}
if(errors.length){console.error('SOURCE-BYTE REGISTRATION validation FAILED');errors.forEach(e=>console.error('- '+e));process.exit(1)} console.log(`SOURCE-BYTE REGISTRATION PASS candidates=${c.candidates.length} receipts=${rr.receipts.length} attempts=${a.attempts.length} raw_byte_verified=${rawCount}`);
