import {useState} from 'react';
import type {EvidenceAssembly,EvidenceFeature} from './types';
import type {SpatialEvidenceGraph} from './graph';
import type {InvestigationCandidate} from './intelligence';
import {runCandidateExperiment,reviewExperiment,createPromotionReceipt,type EvidenceReceipt,type ReceiptContext,type ResearchReview} from './receipts';
import {downloadJson} from './export';
import {formatValue} from './FeaturePanel';

export function InvestigationPanel({assembly,graph,candidates,selected,feature,onCandidate,onLocate,context,journal,onAppend,journalMessage}:{assembly:EvidenceAssembly;graph:SpatialEvidenceGraph;candidates:InvestigationCandidate[];selected:string|null;feature:EvidenceFeature;onCandidate:(id:string)=>void;onLocate:(id:string)=>void;context:()=>ReceiptContext;journal:readonly EvidenceReceipt[];onAppend:(r:EvidenceReceipt)=>Promise<void>;journalMessage:string}){
  const candidate=candidates.find(c=>c.id===selected);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[last,setLast]=useState<EvidenceReceipt|null>(null);
  const [review,setReview]=useState<ResearchReview>({reviewer:'',outcome:'INCONCLUSIVE',note:''});
  const experiment=[...journal].reverse().find(r=>r.kind==='EXPERIMENT'&&(r.payload.data.candidate as {id?:string})?.id===candidate?.id);
  const perform=async(job:()=>Promise<EvidenceReceipt>)=>{setBusy(true);setMessage('');try{const receipt=await job();setLast(receipt);await onAppend(receipt);setMessage(`${receipt.kind} sealed and appended. No archaeological authority was promoted.`);}catch(e){setMessage(String(e));}finally{setBusy(false);}};
  return <>
    <p>Investigation Candidates are computational questions, not discoveries. Review source definitions and null explanations before interpreting a result.</p>
    <label>Investigation candidate<select aria-label="Investigation candidate" value={candidate?.id??''} onChange={e=>onCandidate(e.target.value)}><option value="" disabled>Select a candidate…</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>
    {!candidate&&<div>{candidates.map(c=><button key={c.id} className="evidenceCandidate" onClick={()=>onCandidate(c.id)}><strong>{c.title}</strong><small>{c.authority} · REVIEW REQUIRED</small></button>)}</div>}
    {candidate&&<>
      <span className="evidenceBadge">{candidate.authority} · {candidate.status}</span><h3>{candidate.title}</h3><p>{candidate.detected}</p>
      <div className="evidenceReadout"><small>{candidate.computation.method}</small><p><code>{candidate.computation.expression}</code></p><strong>{typeof candidate.computation.result==='number'?formatValue(candidate.computation.result,candidate.computation.unit):candidate.computation.result??'UNKNOWN'}</strong><p>Uncertainty: {formatValue(candidate.uncertainty.value,candidate.uncertainty.unit)}</p><p>{candidate.uncertainty.note}</p></div>
      <h4>Exact evidence / computation inputs</h4>{candidate.computation.inputs.map(i=><p key={i.id}><code>{i.id}</code><br/>{typeof i.value==='number'?formatValue(i.value,i.unit):i.value??'UNKNOWN'}</p>)}
      <details><summary>Evidence IDs and 3-D locations</summary>{candidate.evidenceIds.map(id=><p key={id}><code>{id}</code></p>)}<div className="actions">{candidate.featureIds.map(id=><button key={id} onClick={()=>onLocate(id)}>{assembly.features.find(f=>f.id===id)?.label??id}</button>)}</div></details>
      <h4>Alternative / null explanations</h4><ul>{candidate.alternatives.map(s=><li key={s}>{s}</li>)}</ul><h4>What would falsify it?</h4><p>{candidate.falsification.test}</p><ul>{candidate.falsification.neededEvidence.map(s=><li key={s}>{s}</li>)}</ul>
      <button disabled={busy} onClick={()=>perform(()=>runCandidateExperiment(candidate,graph,context()))}>Run reproducible computation</button>
      {experiment&&<section><h4>Result → reviewed finding</h4><p>Experiment {experiment.sha256.slice(0,16)}… reproduced source arithmetic. This is not an independent archaeological confirmation.</p><label>Researcher / reviewer<input aria-label="Finding reviewer" value={review.reviewer} maxLength={150} onChange={e=>setReview({...review,reviewer:e.target.value})}/></label><label>Review outcome<select value={review.outcome} onChange={e=>setReview({...review,outcome:e.target.value as ResearchReview['outcome']})}><option>INCONCLUSIVE</option><option>SUPPORTED</option><option>FALSIFIED</option></select></label><label>Evidence interpretation / limitations<textarea aria-label="Finding review note" value={review.note} maxLength={5000} onChange={e=>setReview({...review,note:e.target.value})}/></label><button disabled={busy||!review.reviewer.trim()||review.note.trim().length<10} onClick={()=>perform(()=>reviewExperiment(experiment,review,context()))}>Append reviewed finding</button><small>Operator-supplied, unauthenticated review; geometry authority remains NONE.</small></section>}
    </>}
    <section><h4>Immutable research journal · {journal.length}</h4><p>{journalMessage}</p>{message&&<p role="status">{message}</p>}{last&&<button onClick={()=>downloadJson(`GIZA-${last.kind.toLowerCase()}-${last.sha256.slice(0,12)}.json`,last)}>Download last sealed receipt</button>}<div className="actions"><button onClick={()=>downloadJson('GIZA-investigation-journal.json',{schema:'giza.investigation-journal.v1',receipts:journal})}>Export journal</button></div>{journal.map(r=><details key={r.id}><summary>{r.kind} · {r.payload.context.createdAt}</summary><code>{r.sha256}</code><p>{r.payload.authority} · {r.payload.context.version}</p><button onClick={()=>downloadJson(`GIZA-receipt-${r.sha256.slice(0,12)}.json`,r)}>Export receipt</button></details>)}</section>
    <details><summary>Authority promotion gate</summary><p>Selected: {feature.label}. Source-backed scalar observations are not observed survey surfaces. This explicit gate request records the reasons for denial without changing the feature.</p><label>Reviewer<input aria-label="Promotion reviewer" value={review.reviewer} maxLength={150} onChange={e=>setReview({...review,reviewer:e.target.value})}/></label><label>Reason for request<textarea aria-label="Promotion reason" value={review.note} maxLength={5000} onChange={e=>setReview({...review,note:e.target.value})}/></label><button disabled={busy||!review.reviewer.trim()||review.note.trim().length<10} onClick={()=>perform(()=>createPromotionReceipt(feature,'OBSERVED',graph,review,context()))}>Evaluate OBSERVED promotion · receipt</button></details>
  </>;
}
