import {useState} from 'react';
import {analyzeEvidenceImpact} from './impact';
import {readInvestigations} from './investigations';
import type {EvidenceReceipt} from './receipts';
import type {InvestigationCandidate} from './intelligence';
import {ExplanationPanel} from './ExplanationPanel';
import type {EvidenceAssembly} from './types';
import type {SpatialEvidenceGraph} from './graph';
import {integrateLiveRelation,replayLocalCampaign,replayLocalVerification,registrationVerification,relationImpact,type LiveRelation} from './liveEvidence';
export function LiveEvidencePanel({assembly,graph,records,onAdd,onRemove,experiments,candidates,onInvestigate}:{experiments:readonly EvidenceReceipt[];candidates:InvestigationCandidate[];onInvestigate:()=>void;assembly:EvidenceAssembly;graph:SpatialEvidenceGraph;records:LiveRelation[];onAdd:(r:LiveRelation)=>void;onRemove:(r:LiveRelation)=>void}){
  const [id,setId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [impact,setImpact]=useState<Awaited<ReturnType<typeof analyzeEvidenceImpact>>|null>(null);
  return <section><h4>Live scoped evidence</h4><p>A local replay can connect a reviewed plan relation to this exact assembly snapshot. It cannot place the lid, create 3-D surfaces, or establish site coordinates.</p><label>Local campaign ID<input value={id} onChange={e=>setId(e.target.value)} placeholder="campaign ID from Registration"/></label><button disabled={busy||!id.trim()} onClick={async()=>{setBusy(true);try{const r=await replayLocalCampaign(id,assembly),next=integrateLiveRelation(graph,r,assembly);const saved=await readInvestigations(localStorage.getItem('giza.saved-investigations.v1'));setImpact(await analyzeEvidenceImpact(graph,next,assembly,candidates,experiments,saved));onAdd(r);setMessage('Shared-engine replay and scoped review linked. No canonical geometry changed.');}catch(e){setMessage(String(e));if(String(e).includes('NO_ACTIVE_REVIEWED_REVISION'))for(const r of records)if(r.payload.campaignId===id)onRemove(r);}finally{setBusy(false);}}}>{busy?'Replaying preserved inputs…':'Replay & link scoped evidence'}</button><button disabled={busy||!id.trim()} onClick={async()=>{setBusy(true);try{const replay=await replayLocalVerification(id);setMessage(registrationVerification(replay)+' · '+replay.reason);}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>Replay only · no live promotion</button><p role="status">{message}</p>{impact&&<section><h4>Impact on dependent research</h4><p>Rule: {impact.rule}. No 3-D data was changed by this PLAN_2D relation.</p>{impact.rows.map(row=><article key={row.id}><b>{row.status} · {row.kind}</b><p>{row.reason}</p>{row.paths.map((p,i)=><code key={i}>{p.join(' → ')}</code>)}{row.explanation&&<ExplanationPanel identity={row} load={async()=>row.explanation!}/>}</article>)}{!impact.rows.length&&<p>No saved investigations or experiments are present in this browser.</p>}<button onClick={onInvestigate}>Open linked computation tools</button></section>}{records.map(r=><details key={r.sha256}><summary>{String(r.payload.campaignId)} · {graph.nodes.some(n=>n.id===r.payload.id)?registrationVerification(r):"HISTORICAL — NOT ACTIVE IN THIS SNAPSHOT"}</summary><p>{String(r.payload.classification)} · PLAN_2D_ONLY · {String(r.payload.targetFrame)}</p><p>Operator review and rights declarations are not independently authenticated. Exported claims require replay after import.</p>{relationImpact(graph,r).map(row=><p key={row.featureId}>{row.status}: {row.path.join(' → ')}<br/>{row.reason}</p>)}<button onClick={()=>onRemove(r)}>Detach from this session</button><p>Detaching preserves the campaign and revision. Use Registration rollback to revoke the accepted campaign revision.</p></details>)}</section>;
}
