import {useEffect,useRef,useState} from 'react';
import type {EvidenceAssembly} from './types';
import type {EvidenceReceipt} from './receipts';
import {appendInvestigation,readInvestigations,restoreInvestigation,saveInvestigation,investigationApplicability,type InvestigationDraft,type InvestigationPresentation,type SavedInvestigation} from './investigations';
import {downloadJson} from './export';
import type {CameraBookmark} from './presentation';
const KEY='giza.saved-investigations.v1';
export function SavedInvestigations({assembly,current,draft,presentation,cameraReader,receipts,onRestore,onSaved}:{assembly:EvidenceAssembly;current:EvidenceAssembly;draft:InvestigationDraft;presentation:InvestigationPresentation;cameraReader:()=>CameraBookmark|null;receipts:readonly EvidenceReceipt[];onRestore:(s:SavedInvestigation)=>void;onSaved:()=>void}){
  const [rows,setRows]=useState<SavedInvestigation[]>([]),[title,setTitle]=useState('Khafre feature measurement'),[message,setMessage]=useState('Loading saved investigations…'),[raw,setRaw]=useState<string|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[states,setStates]=useState<Record<string,string>>({});
  const baseline=useRef<string|null>(null),input=useRef<HTMLInputElement>(null);
  useEffect(()=>{let live=true;try{const bytes=localStorage.getItem(KEY);baseline.current=bytes;readInvestigations(bytes).then(saved=>{if(live){setRows(saved);setReady(true);setMessage('Local browser storage is not an archival or multi-user repository. Export for durable custody.');}}).catch(e=>{if(live){setRaw(bytes);setMessage(`Stored bytes preserved; restore blocked: ${String(e)}`);}});}catch(e){setMessage(String(e));}return()=>{live=false;};},[]);
  useEffect(()=>{let live=true;Promise.all(rows.map(async r=>[r.id,await investigationApplicability(r,current)])).then(pairs=>{if(live)setStates(Object.fromEntries(pairs));});return()=>{live=false;};},[rows,current]);
  const append=async(record:SavedInvestigation)=>{if(!ready)throw new Error('Resolve preserved storage before appending; export remains available');const next=await appendInvestigation(localStorage,KEY,baseline.current,record);baseline.current=next.baseline;setRows(next.rows);};
  const save=async(exportOnly=false)=>{setBusy(true);try{const record=await saveInvestigation(title,assembly,draft,{...presentation,camera:cameraReader()},receipts);if(exportOnly){downloadJson('GIZA-investigation.json',record);setMessage('Exported verified snapshot; browser storage unchanged.');}else{await append(record);onSaved();setMessage('Saved with original geometry, canonical points and reproducible result.');}}catch(e){setMessage(String(e));}finally{setBusy(false);}};
  return <section aria-label="Saved investigations"><h4>Save / restore investigation</h4><p>Complete a measurement first. Physical inputs and result are archived separately from camera, visibility and inspection state.</p><label>Investigation title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><div className="actions"><button disabled={busy||!ready} onClick={()=>void save()}>Save investigation</button><button disabled={busy} onClick={()=>void save(true)}>Export investigation</button><button disabled={busy||!ready} onClick={()=>input.current?.click()}>Import investigation</button></div><input ref={input} type="file" accept="application/json,.json" hidden aria-label="Import saved investigation" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{if(file.size>8_000_000)throw new Error('Import exceeds 8 MB');const record=await restoreInvestigation(await file.text());await append(record);setMessage('Imported and replay-verified. Open the saved snapshot below. Identical duplicates are safe.');}catch(error){setMessage(`Import rejected; original file unchanged: ${String(error)}`);}finally{setBusy(false);e.target.value='';}}}/><p role="status">{message}</p>{raw!==null&&<button onClick={()=>downloadJson('GIZA-preserved-investigation-bytes.txt',raw)}>Export corrupt original bytes</button>}{rows.map(row=><article key={row.id}><b>{row.payload.title}</b><p>{states[row.id]??'CHECKING'} · {row.payload.result.value??'UNKNOWN'} {row.payload.result.unit}</p><small>{row.payload.createdAt} · snapshot {row.payload.snapshotSha256.slice(0,12)}</small><div className="actions"><button onClick={()=>{onRestore(row);setMessage('Opened ORIGINAL snapshot. Old points have not been attached to current geometry.');}}>Open saved snapshot</button><button onClick={()=>downloadJson('GIZA-investigation.json',row)}>Export saved record</button></div></article>)}</section>;
}
